/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIHealthCard: typeof import('./src/components/AIHealthCard.vue')['default']
    BodyStatusChart: typeof import('./src/components/BodyStatusChart.vue')['default']
    CalendarView: typeof import('./src/components/CalendarView.vue')['default']
    CycleCard: typeof import('./src/components/CycleCard.vue')['default']
    CycleTrendChart: typeof import('./src/components/CycleTrendChart.vue')['default']
    HealthRecordForm: typeof import('./src/components/HealthRecordForm.vue')['default']
    MoodChart: typeof import('./src/components/MoodChart.vue')['default']
    PainChart: typeof import('./src/components/PainChart.vue')['default']
    QuickRecord: typeof import('./src/components/QuickRecord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticCard: typeof import('./src/components/StatisticCard.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
